# Generated by Django 2.0.4 on 2018-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180529_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('blog_id', models.ForeignKey(on_delete=True, to='cmdb.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user_name',
            field=models.ForeignKey(on_delete=True, to='cmdb.Users'),
        ),
        migrations.AddField(
            model_name='commentreview',
            name='comment_id',
            field=models.ForeignKey(on_delete=True, to='cmdb.BlogComment'),
        ),
        migrations.AddField(
            model_name='commentreview',
            name='reviewer_id',
            field=models.ForeignKey(on_delete=True, to='cmdb.Users'),
        ),
    ]
