# Generated by Django 2.0.4 on 2018-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20180604_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='identity',
            field=models.CharField(choices=[('w', 'writer'), ('e', 'editor')], max_length=1, null=True, verbose_name='身份'),
        ),
    ]
