# Generated by Django 2.0.4 on 2018-06-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_users_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_atten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(verbose_name='用户id')),
                ('flower_id', models.IntegerField(verbose_name='关注人id')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
