# Generated by Django 2.0.4 on 2018-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_user_atten'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contact_wey',
            field=models.CharField(default='none', max_length=20, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='users',
            name='publishers_name',
            field=models.CharField(default='none', max_length=20, verbose_name='出版商名字'),
        ),
    ]
