# Generated by Django 2.0.4 on 2018-06-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20180613_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='identity',
            field=models.CharField(choices=[('w', 'writer'), ('e', 'editor')], default='w', max_length=1, verbose_name='身份'),
        ),
    ]
