# Generated by Django 2.0.4 on 2018-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20180613_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建者名字'),
        ),
    ]
