# Generated by Django 2.0.4 on 2018-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20180617_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_atten',
            name='flower_contact',
            field=models.CharField(default='none', max_length=20, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='user_atten',
            name='article_id',
            field=models.IntegerField(verbose_name='文章id'),
        ),
        migrations.AlterField(
            model_name='user_atten',
            name='flower_id',
            field=models.CharField(max_length=20, verbose_name='关注人账户名'),
        ),
    ]
