# Generated by Django 2.0.4 on 2018-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_auto_20180617_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
